### ISSUE TITLE
iTunes connection

### ISSUE THREAD

**Issue by Depechie** [scott-t/iMote#1]
Tried the iMote DACP connection, but the code won't parse the tunes.DoPair() response from iTunes?

Any suggestions...?

**Comment by scott-t** [comment]
Hmm.  I haven't touched this code for a while, nor do I actively use it - it's possible the iTunes response has changed in later versions I guess.  Are you able to debug it at all?

**Comment by Depechie** [comment]
Well, I got it running indeed... but first thing it needs to do is perform the tuner.Login and inside the GetDAAP method after sending the url it's fails. I think on the return value handling... ( not sure anymore ) Would love to get this up and running again, but don't understand the DAAP protocol. So any hints are welcome ;)

**Comment by scott-t** [comment]
Have just tried to set up some form of debug environment but can't get iTunes (in a VM) to see my app (debugging natively) for the initial pairing.  

Just poking through the code now, this wouldn't be something as simple as the predefined IP address of the iTunes instance (TunesRemote.cs, Ln 55)?  Ideally that wouldn't be hardcoded and I only just noticed it was still there.

**Comment by Depechie** [comment]
No no... like I said, I tweaked it so that I see it connecting to iTunes :) ( in other words, I entered my own ip address )
Also needed to get the Microsoft.WindowsAPICodePack, because it was not in the source code/references.

Is there an easy way to 'debug' the traffic from and to iTunes? Could take a look myself this evening...

**Comment by scott-t** [comment]
Heh.  Guess this is why READMEs are a good idea :)

I _think_ it came from here http://archive.msdn.microsoft.com/WindowsAPICodePack (wasn't sure on redist- licencing for it).  Just download and grab the primary dll (and the shell dll).    From memory, ZeroConf came from http://code.google.com/p/zeroconfignetservices/ if you don't have it yet.

**Comment by Depechie** [comment]
All worked out yesterday héhé... so only thing missing is a good knowledge of how to parse the daap responses from itunes :)

**Comment by scott-t** [comment]
Ah.  Right - getting late here and could probably use some sleep, so misreading :)  DAAP itself isn't my strong point, hence grabbed the DAAP-Sharp library which worked fine at the time.  Best of luck with the debugging - if you can trace back where it dies, should be able to work out what's missing.

I'm assuming the fail is then on the return DAAP.ContentParser.Parse(bag, b, root); ?

**Comment by Depechie** [comment]
Yep indeed!

**Comment by Depechie** [comment]
In the Login method in TunesRemote there is following code: node = GetDAAP("databases"); this will trigger an endless loop.
In other words pairing and the actual login are a success, but retrieving info from itunes to populate the mainscreen isn't working.

**Comment by Depechie** [comment]
Other implementations I've found but also unable to get it working ( maybe you know more on how to get this merged with iMote? ):
https://zeroconf.codeplex.com ( has DACP class )
https://github.com/gburt/dmap-sharp > uses http://www.mono-project.com/Mono.Zeroconf ( has DACP class )

**Comment by scott-t** [comment]
Unless I can get a work test environment again, I'm not sure I'll be able to look at changing too much.  Any chance you could upload a binary dump of the response from iTunes when doing the databases call (contents of byte[] b  just prior to ContentParser.Parse())?

Another (easy) thing to try is swapping out ContentCodeBag.cs (and possibly ContentParser) with the ones from here: https://github.com/gburt/dmap-sharp/tree/master/src/Dmap  Looks like an updated version of what I originally used.

**Comment by scott-t** [comment]
@Depechie Have you had a chance to swap out the Content cs files with the updated ones?  I'm curious if that might be enough to fix it :)

**Comment by Depechie** [comment]
Hey Scott, I'm curious too :D but haven't found new time to dig in 'yet'... will try to pick it up again next weekend!
